import type { Metadata } from "next";
import Sidebar from "@/app/components/cores/sidebar";
import Header from "../components/cores/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div>
        <div className='grid grid-cols-5'>
        <div className="col-span-1">
          <Sidebar/>
        </div>
        <div className="col-span-4">
        <div>
        <Header/>
        </div>
          {children}
        </div>
        </div>
      </div>
  );
}
